# Generated by Django 6.0.2 on 2026-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CancelledOrders",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reason", models.TextField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "Cancelled Orders",
                "db_table": "cancelled_orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Donations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("donation_type", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField()),
                ("item_name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.CharField(blank=True, max_length=100, null=True)),
                ("item_image", models.CharField(blank=True, max_length=100, null=True)),
                ("pickup_address", models.TextField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_screenshot",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("profession", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("time_slot", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Donations",
                "db_table": "donations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "price_at_purchase",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "verbose_name_plural": "Order Items",
                "db_table": "order_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("shipping_address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=20)),
                ("payment_method", models.CharField(max_length=20)),
                ("is_paid", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "Orders",
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrdersCart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "Order Carts",
                "db_table": "orders_cart",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrdersCartitem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("added_at", models.DateTimeField()),
                ("unit_value", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                "verbose_name_plural": "Order Cart Items",
                "db_table": "orders_cartitem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image_url", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "Product Images",
                "db_table": "product_images",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductReviews",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "Product Reviews",
                "db_table": "product_reviews",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=50)),
                (
                    "stock_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("average_rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("rating_count", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "Products",
                "db_table": "products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductVariants",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
            ],
            options={
                "verbose_name_plural": "Product Variants",
                "db_table": "product_variants",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserAddresses",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("town_city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=120)),
                ("pincode", models.CharField(max_length=10)),
                ("is_default", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("area_street_sector", models.CharField(max_length=255)),
                ("delivery_instructions", models.TextField(blank=True, null=True)),
                ("flat_house_building", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("landmark", models.CharField(blank=True, max_length=255, null=True)),
                ("mobile_number", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "User Addresses",
                "db_table": "user_addresses",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfiles",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(max_length=20, unique=True)),
                ("password_hash", models.TextField()),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("category", models.CharField(max_length=30)),
                ("address_line", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("state", models.CharField(blank=True, max_length=120, null=True)),
                ("country", models.CharField(blank=True, max_length=120, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("location_url", models.TextField(blank=True, null=True)),
                ("profile_pic_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AutoScrollImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="auto_scroll_images/")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the image",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to hide this image from the scroll",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Auto Scroll Image",
                "verbose_name_plural": "Auto Scroll Images",
                "db_table": "auto_scroll_images",
                "ordering": ["order", "-created_at"],
                "managed": True,
            },
        ),
    ]
