# Generated by Django 6.0.2 on 2026-02-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_admin", "0002_autoscrollimage_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoscrollimage",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary URL link (auto-generated upon save)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="autoscrollimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload image here; it will be stored in Cloudinary",
                null=True,
                upload_to="auto_scroll_images/",
            ),
        ),
    ]
