# Generated by Django 6.0.2 on 2026-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoscrollimage",
            name="placement",
            field=models.CharField(
                choices=[
                    ("top", "Top/Upper Scrollbar"),
                    ("bottom", "Bottom/Lower Scrollbar"),
                    ("other", "Other/General"),
                ],
                default="top",
                help_text="Which slider this image belongs to",
                max_length=20,
            ),
        ),
    ]
